Repository thanh-cnguyen/ai_lang_master, pull requests merged in 2024-12, with the labels that each got.

#4 Prompt the AI to make the user ask questions in the supported languag…
  chatbot/nlp_models/gpt_model.py
Labels: enhancement, python

#5 Language based voice listener
  frontend/src/components/ChatContainer.js
  frontend/src/styles/base.scss
Labels: enhancement, javascript

#8 OpenAIVersion
  Dockerfile
  requirements.txt
Labels: bug, python

#9 Update readme
  README.md
Labels: documentation

#10 Reorganize references in README.md
  README.md
Labels: documentation

#11 Update README.md
  README.md
Labels: documentation

#12 Update README.md
  README.md
Labels: documentation
